### ISSUE TITLE
Noise-free EDA features

### ISSUE THREAD

**Issue by SJKOL** [PCdLf/wearables#10]
To be able to calculate noise free EDA features, all EDA data needs to be marked with information from the artefacts file (per 5 seconds: noise/ noise-free). 
Current UMCU solution: fuzzy join EDA file (timestamp) with artefact file (5 second period). But there may be more effecient ways?

@RemkoDuursma @keesdeschepper @PCdLf

**Comment by keesdeschepper** [comment]
@SJKOL the timestamp (say 2000-01-01 22:33:44.125) in the artifact file is always also a timestamp in the EDA file?

**Comment by PCdLf** [comment]
Done, with labeling of the artifacts
