### ISSUE TITLE
No peaks

### ISSUE THREAD

**Issue by PCdLf** [PCdLf/wearables#11]
If there are no peaks in a given time period, then the app forecloses.

INFO [2021-10-25 11:24:59] IBI data analyzed.
INFO [2021-10-25 11:24:59] EDA data filtered.
Warning: Error in *: non-numeric argument to binary operator
  1: runApp

**Comment by PCdLf** [comment]
The peaks in the file that was analyzed did not meet the threshold in the find_peaks function. When the threshold was set to 0.005 the problem was solved. So the function should throw an error if the find_peaks function does not find peaks above the threshold.

**Comment by PCdLf** [comment]
I think the error should be thrown in the remove_small_peaks function as the threshold is used in that function.

**Comment by moturoa** [comment]
Fixed
