### ISSUE TITLE
raw EDA instead of filtered data?

### ISSUE THREAD

**Issue by tleutritz-ukw** [PCdLf/wearables#13]
[Here](https://github.com/PCdLf/wearables/blob/70583519a386a5e5b31ba480888196671ddd89d4/R/peak_detection.R#L354) the columns "EDA" is selected isntead of "filtered_eda", which I would select for further processing - or is this otherwise justified?

**Comment by PCdLf** [comment]
Hi tleutritz,

thank you for the comment. I will look into your issue as soon as possible. We hope to work on the package later this year, to further develop the Shiny app and wearables package. 

Best,

**Comment by PCdLf** [comment]
Hi tleuritz-ukw,

I've had a chance to look into the code and SVM classifier. In the paper by Taylor (2015) "Automatic Identification of Artifacts in Electrodermal Activity Data" they explain how the feature selection (Table 4) was done, and why you would sometimes use the filtered (upsampled/downsampled) signal and sometimes the raw signal. We've made a direct integration of the Python code into the R package, so we follow their rationale for this particular algorithm. I hope to also compare some additional settings and other algorithms for peak detection and artifact detection as well.
