### ISSUE TITLE
wrong variable name used for data from RHRV analysis

### ISSUE THREAD

**Issue by tleutritz-ukw** [PCdLf/wearables#14]
within [this line](https://github.com/PCdLf/wearables/blob/a820b2fcd3efaf7f92c167db3913a02f9a267ea3/R/ibi_analysis.R#L73) the wrong variable name is used to fetch the results from RHRV - instead it should be LFHF, i.e.

`LFHF = mean(freq$LFHF),`

(for reference see [here](https://github.com/cran/RHRV/blob/master/R/CalculatePowerBand.R#L103) and [here](https://github.com/cran/RHRV/blob/master/R/CalculatePowerBand.R#L127) in RHRV code for powerband calculation)

**Comment by PCdLf** [comment]
Hi tleuritz,

we hope to start working on the package again later this year, and will make sure to check this out as well.

Best, Peter

**Comment by PCdLf** [comment]
Issue solved in the new version.
