### ISSUE TITLE
Check adjusted or new Nowatch datasets

### ISSUE THREAD

**Issue by hypebright** [PCdLf/wearables#26]
See [this issue](https://github.com/PCdLf/wearalyze/issues/12) in wearalyze.

Currently we're expecting the following files:

"activity_type.csv",
"activity_cadence.csv",
"activity_count.csv",
"temperature.csv",
"cortisollevels.csv",
"heartbeats.csv",
"heart_rate.csv",
"resting_heart_rate.csv",
"respiration_rate.csv",
"sleep_session.csv",
"stress_level.csv"

It seems there can be other files too. @PCdLf can you check if anything did change and what dataset we should add or adjust by name?

**Comment by hypebright** [comment]
Besides that we need an extended check in `aggregate_nowatch_data` as it now only checks if the activity data is there.

**Comment by hypebright** [comment]
> Besides that we need an extended check in `aggregate_nowatch_data` as it now only checks if the activity data is there.

Seems like this is all we need, datasets that are not listed are included as well (uppercase with original name), and for example SKIN_CONDUCTANCE can be re-labelled to EDA to make it consistent between other devices.

**Comment by PCdLf** [comment]
I checked the aggregated biomarker datasets, and these are similar to the ones from earlier this year.

**Comment by hypebright** [comment]
@PCdLf thanks for checking, I think you can merge and close #27 now 👍, this issue will automatically be closed once merged
