### ISSUE TITLE
Check if parameters from batch are correct

### ISSUE THREAD

**Issue by PCdLf** [PCdLf/wearables#5]
Process some testfiles to see if the code extracts the correct features.

**Comment by SJKOL** [comment]
I will test with a few EDA files if python EDA Explorer and our package yield the same result.

**Comment by SJKOL** [comment]
1. I noticed that the function find_peaks it not yet called in read_and_process_e4. Should be added.
2. To get the same output as python a few steps should be taken that are now put in a function named write_peak_features. Probably just add those last steps to find_peaks function.
3. R currently finds much more peaks than python (1786 vs 705). Moreover, for the same peak, the calculated features are different (mainly from amp feature onward). R code must be thouroughly checked.

**Comment by PCdLf** [comment]
Is this fixed? Or do we have a problem with the peak detection code?

**Comment by keesdeschepper** [comment]
So last time we noticed that in python one half of the peak features was based on eda, and the other half on filtered_eda. That made for some strange results. So we decided to go for filtered_eda all the way. However, this makes comparison of the python and R code a bit harder. I'll see what I can do, but my interpretation of the priorities was dashboard and performance first.

**Comment by PCdLf** [comment]
Hi @keesdeschepper, did you ever check this? We are working on the new version right now, and were curious of this was still something that we wanted to test, considering that eda-explorer used half of the raw and half of the filtered data? It is therefore wrong by definition. I am closing this for now.
