### ISSUE TITLE
Report features

### ISSUE THREAD

**Issue by PCdLf** [PCdLf/wearables#6]
What features do you need in the report?

**Comment by SJKOL** [comment]
Wij (UMCU) berekenen nu:

Per 5 minuten (in de timeframe -30 tot +15 relatief tot agressie incident):
1. EDA_artefact_percent: hoeveel % van de 5 minuten EDA data bevat ruis?
2. EDA_minuten_zonder_noise: hoeveel minuten zijn ruisvrij?
3. EDA_mean: het gemiddelde van alle ruisvrije EDA momenten
4. EDA_peaks_sum: het aantal gevonden pieken in die 5 minuten (alleen ruisvrije momenten)
5. EDA_peaks_meanPPM: aantal pieken (ruisvrije momenten) gedeeld door de ruisvrije tijd
6. ACC_mean: gemiddelde van acceleratie
7. TEMP_mean: gemiddelde van temperatuur
8. HR_mean: gemiddelde van Empatica hartslag.

In de uiteindelijke analyse nemen we alleen 5-minuten segmenten mee met <75% ruis.

**Comment by SJKOL** [comment]
Suggestie van collega's was om ook andere aggregaties toe te voegen, die veel meer kunnen zeggen dan alleen een gemiddelde: bv variance, sdv, min, max, skewness, kurtosis.

Daarnaast ook behalve een timeframe van 5 minuten kortere segmenten als extra features: bv 1 minuut, 30 seconden.

Je zou vervolgens een machine learning aanpak kunnen doen: De data labelen als rood (aggressie), evt geel (spanning), groen (niks), en dan een classifier trainen met alle features. Het algoritme kijkt dan zelf waar de meeste informatie inzit. Zie bv: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6988899/

**Comment by SJKOL** [comment]
If i saw correctly, currently features from EDA are printed which are only to be used internally for the artefact classifier. The features to be used for further analysis are the results from the peak detection. We (UMCU) currently only are interested in peaks per minute.

**Comment by PCdLf** [comment]
Simpele aggregatie voor Report gemaakt. 
Uitgebreidere summary voor de RDS bestanden
