### ISSUE TITLE
Timezone calendar/server

### ISSUE THREAD

**Issue by PCdLf** [PCdLf/wearables#7]
Is the timezone correct in the calendar and on the server?

**Comment by keesdeschepper** [comment]
@PCdLf Does this only apply to the dashboard?

**Comment by PCdLf** [comment]
The timezones on the server side need to be fixed, and don't show the graphs properly, check what is happenig

**Comment by PCdLf** [comment]
This is mainly a problem if you run RStudio on a server that does not have the same timezone as you want for your data analysis. Users should be aware that the timing might be off if they use those servers.
